version: "3.5"

services:
  postgres:
    image: postgres
    networks:
      - postgres_net
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    volumes:
      - ./postgresql:/var/lib/postgresql
      - ./postgresql_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=root
      - PGADMIN_PORT=5050
    volumes:
      - ./pgadmin:/root/.pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres_net
    restart: unless-stopped

networks:
  postgres_net:
    driver: bridge

